all: abdeltwab output_program simple_program

abdeltwab: abdeltwab.c
	gcc abdeltwab.c -o abdeltwab

output_program: abdeltwab.c abdeltwab.c
	gcc abdeltwab.c abdeltwab.c -o output_program

simple_program: simple_program.c
	gcc simple_program.c -o simple_program

clean:
	rm -f process_creation output_program simple_program
